server.port=8080
spring.kafka.bootstrap-servers=broker:9092
spring.kafka.consumer.group-id=multithread-group
kafka.listener.concurrency=4
kafka.topic.name=emails
kafka.topic.partitions=6
async.core-pool-size=8
async.max-pool-size=16
async.queue-capacity=1000
async.thread-name-prefix=async-
kafka.consumer.max-poll-records=500
kafka.producer.linger-ms=5
kafka.producer.batch-size=32768
kafka.producer.compression-type=lz4
